### ISSUE TITLE
表示内容が基準点成果等閲覧サービスの内容と異なる

### ISSUE THREAD

**Issue by yosimusakun** [gsi-cyberjapan/experimental_cp#1]
表題の通り，基準点ベクトルタイルとして渡ってくる一部基準点が，基準点成果等閲覧サービスのものと異なります．
具体的に，TR45334160001は現在(2020/03/12)基準点タイルでは成果公表停止中となっていますが，
一方で基準点成果等閲覧サービスでは正常となっています．
TR45334160001の 基準点成果情報登録日時は，2020/01/14と割と最近のため更新が追い付いていないのかと一瞬疑いましたが，基準点ベクトルタイルは毎週更新予定とありました．
ではなぜ表示内容が異なるのでしょうか？
ご回答のほどよろしくお願いいたします．

**Comment by johofukyu** [comment]
お問合せいただきありがとうございます。

現在基準点ベクトルタイルは毎週の更新は行っておらず、不定期更新となっております。「データは毎週更新予定です。」と誤った情報を掲載しており、まことに申し訳ございません。

また、本件は提供実験の位置づけで行っておりますので、ご理解いただければと思います。
引き続きよろしくお願いします。

**Comment by yosimusakun** [comment]
迅速なご回答ありがとうございます．
承知いたしました．
